sudo: required
services:
  - docker

before_install:
  - docker build -t faizan2590/docker_test -f Dockerfile.dev .

script:
  - docker run faizan2590/docker_test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker_test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-eu-central-1-984500369625"
  bucket_path: "docker_test"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
